---
title: Omar Guendeli
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Omar Guendeli
email: guendeliomar@gmail.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
parallax_image_one: assets/images/startup3.jpg
parallax_image_two: assets/images/startup3.jpg
project_one: First Project
project_one_description: Describe your project!
project_one_url: https://github.com/jameshamann/jekyll-material-theme
project_one_icon: location_on
project_two: Second Project
project_two_description: Describe your project!
project_two_url: https://github.com/jameshamann/jekyll-material-theme
project_two_icon: photo_camera
project_three: Third Project
project_three_description: Describe your project!
project_three_url: https://github.com/jameshamann/jekyll-material-theme
project_three_icon: hotel
project_four: Fourth Project
project_four_description: Describe your project!
project_four_url: https://github.com/jameshamann/jekyll-material-theme
project_four_icon: restaurant
project_button: Github
github: https://github.com/jameshamann/jekyll-material-theme
medium: https://medium.com
baseurl: 
url: http://localhost:4000/
google_analytics_tracking_id: 
cookies_banner: show
cookie_accept_message: Thanks!
markdown: kramdown
permalink: pretty
plugins:
- jekyll-feed
- jekyll-assets
- jekyll-minifier
